[package]
name = "freedesktop-desktop-entry"
version = "0.3.3"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"
homepage = "https://codeberg.org/mmstick/freedesktop-desktop-entry"
repository = "https://codeberg.org/mmstick/freedesktop-desktop-entry"
description = "Freedesktop Desktop Entry Specification"
license = "MIT/Apache-2.0"
readme = "README.md"
categories = [ "os::unix-apis" ]
keywords = [ "freedesktop", "desktop", "entry" ]
maintenance = { status = "passively-maintained" }

[dependencies]
dirs = "3"
memchr = "2"
thiserror = "1"
